name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

# C# backend ---
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '10.0.x'

    - name: Build C# code
      run: dotnet build

    - name: Run C# tests
      run: dotnet test

# TS frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '24.x'

    - name: Install npm dependencies
      run: npm install
      working-directory: DotnetTemplate.Web

    - name: Build TypeScript code
      run: npm run build
      working-directory: DotnetTemplate.Web

    - name: Run TypeScript linter
      run: npm run lint
      working-directory: DotnetTemplate.Web

    - name: Run TypeScript tests
      run: npm test
      working-directory: DotnetTemplate.Web